add infrastructure progress report 2404
icon-project/grants-program pull request #96
Opened 2024-04-01 18:47 UTC by robcxyz

2024-04-08 22:35 UTC, CyrusVorwald requested changes

2024-04-08 22:35 UTC, CyrusVorwald commented on progress-reports/infrastructure/2404-infrastructure-progress-report.md
> +This is a progress update for 3/2023 on infrastructure provided by sudoblock including development of the tracker, indexer, and operation of RPC endpoints being used to support the ICON ecosystem.
should be 3/2024

2024-05-14 18:06 UTC, robcxyz commented
@CyrusVorwald - Fixed

2024-05-14 20:34 UTC, CyrusVorwald approved these changes

2024-05-14 20:34 UTC, merged